<script setup lang="ts">
/* eslint vue/singleline-html-element-content-newline: "off", vue/max-attributes-per-line: "off", vue/html-self-closing: "off" */
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { AlertCircle, Check, Clock, FilePenLine, Save, UserRoundX } from 'lucide-vue-next'
import InitialsAvatar from '@/components/InitialsAvatar.vue'
import StatePanel from '@/components/StatePanel.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import { ApiError, apiFetch, shortDate, shortTime } from '@/lib/api'
import type { AttendanceResponse, AttendanceRosterItem, AttendanceStatus } from '@/lib/types'

const route=useRoute();const sessionId=String(route.params.sessionId)
const data=ref<AttendanceResponse|null>(null);const roster=ref<AttendanceRosterItem[]>([]);const loading=ref(true);const saving=ref(false);const error=ref('');const saved=ref(false);const search=ref('')
const dirty=ref(false)
const filtered=computed(()=>roster.value.filter(person=>person.participantName.toLocaleLowerCase('tr-TR').includes(search.value.toLocaleLowerCase('tr-TR'))))
const completed=computed(()=>roster.value.filter(person=>person.status).length)
const options:Array<{value:AttendanceStatus;label:string;icon:typeof Check}>=[{value:'present',label:'Geldi',icon:Check},{value:'absent',label:'Gelmedi',icon:UserRoundX},{value:'late',label:'Gecikti',icon:Clock},{value:'excused',label:'Mazeretli',icon:FilePenLine},{value:'makeup_required',label:'Telafi Gerekli',icon:AlertCircle}]

async function load(){loading.value=true;error.value='';try{data.value=await apiFetch<AttendanceResponse>(`/sessions/${sessionId}/attendance`);roster.value=data.value.roster.map(item=>({...item}));dirty.value=false}catch(cause){error.value=cause instanceof Error?cause.message:'Yoklama alınamadı.'}finally{loading.value=false}}
function setStatus(person:AttendanceRosterItem,status:AttendanceStatus){person.status=status;dirty.value=true;saved.value=false}
function markAll(){if(!globalThis.confirm('Listedeki tüm kursiyerler geldi olarak işaretlensin mi?'))return;roster.value.forEach(person=>person.status='present');dirty.value=true;saved.value=false}
async function save(){saving.value=true;error.value='';try{await apiFetch(`/sessions/${sessionId}/attendance`,{method:'PUT',body:JSON.stringify({records:roster.value.map(({enrollmentId,status,note})=>({enrollmentId,status,note:note||null}))})});dirty.value=false;saved.value=true}catch(cause){error.value=cause instanceof ApiError?cause.message:'Yoklama kaydedilemedi.'}finally{saving.value=false}}
function beforeUnload(event:InstanceType<typeof globalThis.Event>){if(dirty.value)event.preventDefault()}
onMounted(()=>{load();globalThis.addEventListener('beforeunload',beforeUnload)});onBeforeUnmount(()=>globalThis.removeEventListener('beforeunload',beforeUnload))
</script>

<template>
  <StatePanel v-if="loading" state="loading" />
  <StatePanel v-else-if="error&&!data" state="error" :message="error" @retry="load" />
  <template v-else-if="data">
    <div class="attendance-head"><div><p class="eyebrow">Yoklama</p><h1>{{ data.session.courseName }}</h1><p>{{ shortDate(data.session.startsAt) }} · {{ shortTime(data.session.startsAt) }}–{{ shortTime(data.session.endsAt) }} · {{ data.session.laneName || 'Kulvar belirtilmedi' }}</p></div><div class="page-actions"><StatusBadge :tone="dirty?'warning':saved?'success':'neutral'" :label="dirty?'Kaydedilmemiş değişiklik':saved?'Kaydedildi':'Değişiklik yok'" /><button class="button button--secondary" type="button" @click="markAll"><Check :size="18" />Tümünü Geldi İşaretle</button></div></div>
    <div v-if="error" class="notice notice--danger" role="alert"><AlertCircle :size="18" />{{ error }}</div>
    <div class="attendance-toolbar"><label class="field"><span>Kursiyer ara</span><input v-model="search" type="search" placeholder="Ad soyad" /></label><div><span>Tamamlanan</span><strong>{{ completed }}/{{ roster.length }}</strong></div></div>
    <section v-if="filtered.length" class="attendance-list" aria-label="Kursiyer yoklama listesi"><article v-for="person in filtered" :key="person.enrollmentId" class="attendance-row"><div class="attendance-person"><InitialsAvatar :name="person.participantName" /><div><strong>{{ person.participantName }}</strong><span v-if="person.guardianName">Veli: {{ person.guardianName }}</span><StatusBadge v-if="person.paymentAttention" tone="warning" label="Ödeme dikkat" /></div></div><div class="attendance-options" role="group" :aria-label="`${person.participantName} yoklama durumu`"><button v-for="option in options" :key="String(option.value)" type="button" :class="[`status-${option.value}`,{selected:person.status===option.value}]" :aria-pressed="person.status===option.value" @click="setStatus(person,option.value)"><component :is="option.icon" :size="19" /><span>{{ option.label }}</span></button></div><label class="attendance-note"><span class="sr-only">{{ person.participantName }} notu</span><input v-model="person.note" placeholder="İsteğe bağlı kısa not" @input="dirty=true;saved=false" /></label></article></section>
    <StatePanel v-else state="empty" title="Kursiyer bulunamadı" message="Arama ölçütünü değiştirin veya aktif kurs listesini kontrol edin." />
    <footer class="save-bar"><span><b>{{ completed }}</b> / {{ roster.length }} kursiyer işaretlendi</span><button class="button button--primary" type="button" :disabled="saving||!dirty" @click="save"><Save :size="18" />{{ saving?'Kaydediliyor…':'Yoklamayı Kaydet' }}</button></footer>
  </template>
</template>

<style scoped>
.attendance-head{display:flex;justify-content:space-between;gap:20px;margin:-24px -24px 20px;padding:20px 24px;background:#fff;border-bottom:1px solid #d8e2ee}.attendance-head h1{margin:0;font-size:27px}.attendance-head p:not(.eyebrow){margin:8px 0 0;color:#5d6875}.attendance-toolbar{display:flex;align-items:end;gap:20px;padding:14px 16px;background:#edf4ff;border:1px solid #c1c7d2}.attendance-toolbar .field{width:min(360px,100%);grid-column:auto}.attendance-toolbar>div{margin-left:auto;text-align:right}.attendance-toolbar>div span,.attendance-toolbar>div strong{display:block}.attendance-toolbar>div span{font-size:11px;text-transform:uppercase;color:#49607c}.attendance-toolbar>div strong{font-size:22px}.attendance-list{border:1px solid #c1c7d2;border-top:0;background:#fff}.attendance-row{display:grid;grid-template-columns:minmax(220px,1fr) auto minmax(150px,.7fr);gap:14px;align-items:center;padding:14px 16px;border-bottom:1px solid #d8e2ee}.attendance-row:last-child{border:0}.attendance-person{display:flex;align-items:center;gap:11px}.attendance-person strong,.attendance-person>div>span{display:block}.attendance-person>div>span{margin:3px 0;color:#5d6875;font-size:11px}.attendance-options{display:flex;gap:7px}.attendance-options button{min-width:90px;min-height:52px;display:flex;align-items:center;justify-content:center;gap:6px;padding:6px 9px;border:1px solid #8fa3b7;border-radius:4px;background:#fff;color:#425263;font-size:11px;font-weight:800}.attendance-options button.selected{color:white;border-color:transparent}.attendance-options .status-present.selected{background:#27845c}.attendance-options .status-absent.selected{background:#ba1a1a}.attendance-options .status-late.selected{background:#a45b00}.attendance-options .status-excused.selected{background:#49607c}.attendance-options .status-makeup_required.selected{background:#005472}.attendance-note input{width:100%;min-height:42px;padding:8px 10px;border:1px solid #8fa3b7;border-radius:4px}.save-bar{position:sticky;bottom:0;display:flex;align-items:center;justify-content:flex-end;gap:20px;margin:20px -24px -24px;padding:14px 24px;background:#fff;border-top:1px solid #c1c7d2}.save-bar span{color:#49607c;font-size:13px}.save-bar b{color:#051d2f}.save-bar .button{min-height:48px;min-width:220px}@media(max-width:1250px){.attendance-row{grid-template-columns:220px 1fr}.attendance-options{overflow:auto}.attendance-note{grid-column:2}}@media(max-width:720px){.attendance-head{margin:-18px -14px 16px;padding:18px 14px;flex-direction:column}.attendance-toolbar{align-items:stretch}.attendance-row{grid-template-columns:1fr;padding:14px}.attendance-options{display:grid;grid-template-columns:repeat(2,1fr)}.attendance-options button{min-width:0}.attendance-options button:last-child{grid-column:1/-1}.attendance-note{grid-column:1}.save-bar{margin:16px -14px -28px;padding:12px 14px;flex-direction:column;align-items:stretch}.save-bar .button{width:100%;min-width:0}.save-bar span{text-align:center}}
</style>
