<script setup lang="ts">
/* eslint vue/singleline-html-element-content-newline: "off", vue/max-attributes-per-line: "off", vue/html-self-closing: "off" */
import { computed, onMounted, ref } from 'vue'
import { ChevronLeft, ChevronRight, Clock, Users, Waves, X } from 'lucide-vue-next'
import StatePanel from '@/components/StatePanel.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import { ApiError, apiFetch, shortDate, shortTime } from '@/lib/api'
import type { LanePlanResponse } from '@/lib/types'
import { useAuthStore } from '@/stores/auth'

const data=ref<LanePlanResponse|null>(null);const loading=ref(true);const error=ref('');const date=ref(new Date().toISOString().slice(0,10));const poolId=ref('');const editing=ref<LanePlanResponse['sessions'][number]|null>(null);const selectedLane=ref('');const saving=ref(false)
const auth=useAuthStore()
const startHour=7;const endHour=23;const hours=Array.from({length:endHour-startHour},(_,index)=>startHour+index)
const activeLanes=computed(()=>data.value?.lanes.filter(lane=>!poolId.value||lane.poolId===poolId.value)||[])
function position(value:string){const d=new Date(value);return ((d.getHours()+d.getMinutes()/60-startHour)/(endHour-startHour))*100}
function width(start:string,end:string){const a=new Date(start);const b=new Date(end);return Math.max(((b.getTime()-a.getTime())/3600000/(endHour-startHour))*100,2)}
function shift(days:number){const next=new Date(`${date.value}T12:00:00`);next.setDate(next.getDate()+days);date.value=next.toISOString().slice(0,10);load()}
async function load(){loading.value=true;error.value='';const params=new globalThis.URLSearchParams({date:date.value});if(poolId.value)params.set('poolId',poolId.value);try{data.value=await apiFetch<LanePlanResponse>(`/lane-plan?${params}`);if(!poolId.value&&data.value.pools[0])poolId.value=data.value.pools[0].id}catch(cause){error.value=cause instanceof Error?cause.message:'Kulvar planı alınamadı.'}finally{loading.value=false}}
function openEdit(session:LanePlanResponse['sessions'][number]){if(!auth.isManager)return;editing.value=session;selectedLane.value=session.poolLaneId}
async function saveLane(){if(!editing.value||!selectedLane.value)return;saving.value=true;error.value='';try{await apiFetch(`/sessions/${editing.value.id}/lane`,{method:'PATCH',body:JSON.stringify({poolLaneId:selectedLane.value,version:editing.value.version})});editing.value=null;await load()}catch(cause){error.value=cause instanceof ApiError?cause.message:'Kulvar atanamadı.'}finally{saving.value=false}}
onMounted(load)
</script>

<template>
  <div class="page-header"><div><p class="eyebrow">Havuz takvimi</p><h1>Havuz ve Kulvar Planı</h1><p>Seansları kulvar ve saate göre izleyin; çakışmalar sunucuda engellenir.</p></div><div class="page-actions"><label class="field pool-select"><span>Havuz</span><select v-model="poolId" @change="load"><option value="">Tüm Havuzlar</option><option v-for="pool in data?.pools||[]" :key="pool.id" :value="pool.id">{{ pool.name }}</option></select></label></div></div>
  <div class="plan-toolbar"><button class="icon-button" aria-label="Önceki gün" @click="shift(-1)"><ChevronLeft :size="20" /></button><strong>{{ shortDate(`${date}T12:00:00`) }}</strong><button class="icon-button" aria-label="Sonraki gün" @click="shift(1)"><ChevronRight :size="20" /></button><button class="button button--secondary" @click="date=new Date().toISOString().slice(0,10);load()">Bugün</button><div class="legend"><span><i class="busy" />Dolu</span><span><i class="empty" />Boş</span><span><i class="maintenance" />Bakım</span><span><i class="closed" />Kapalı</span></div></div>
  <div v-if="error" class="notice notice--danger" role="alert">{{ error }}</div>
  <StatePanel v-if="loading" state="loading" />
  <StatePanel v-else-if="!activeLanes.length" state="empty" title="Kulvar bulunamadı" message="Seçili havuz için tanımlı kulvar yok." />
  <section v-else class="timeline-card" aria-label="Günlük kulvar zaman çizelgesi">
    <div class="timeline-scroll"><div class="timeline" role="table"><div class="timeline-head" role="row"><div class="lane-name head" role="columnheader">Kulvarlar</div><div class="hours"><span v-for="hour in hours" :key="hour">{{ String(hour).padStart(2,'0') }}:00</span></div></div><div v-for="lane in activeLanes" :key="lane.id" class="lane-row" role="row"><div class="lane-name" role="rowheader"><Waves :size="18" /><div><strong>{{ lane.name }}</strong><span>{{ lane.subtitle||'Havuz kulvarı' }}</span></div></div><div class="lane-track"><i v-for="hour in hours" :key="hour" class="gridline" /><button v-for="session in data?.sessions.filter(item=>item.poolLaneId===lane.id)||[]" :key="session.id" class="session-block" :class="`session-${session.status||'active'}`" :style="{left:`${position(session.startsAt)}%`,width:`${width(session.startsAt,session.endsAt)}%`}" :title="`${session.courseName}, ${shortTime(session.startsAt)} - ${shortTime(session.endsAt)}`" @click="openEdit(session)"><strong>{{ shortTime(session.startsAt) }} · {{ session.courseName }}</strong><span>{{ session.instructorName||'Eğitmen bekliyor' }}</span><small v-if="session.capacity"><Users :size="12" />{{ session.enrolledCount||0 }}/{{ session.capacity }}</small></button></div></div></div></div>
  </section>
  <div v-if="editing" class="drawer-backdrop" @click.self="editing=null"><aside class="drawer" role="dialog" aria-modal="true" aria-labelledby="drawer-title"><header><div><p class="eyebrow">Kulvar Ataması</p><h2 id="drawer-title">{{ editing.courseName }}</h2></div><button class="icon-button" aria-label="Kapat" @click="editing=null"><X :size="20" /></button></header><div class="drawer__body stack"><div class="notice"><Clock :size="18" /><span>{{ shortDate(editing.startsAt) }} · {{ shortTime(editing.startsAt) }}–{{ shortTime(editing.endsAt) }}</span></div><label class="field field--full"><span>Yeni Kulvar</span><select v-model="selectedLane"><option v-for="lane in activeLanes" :key="lane.id" :value="lane.id">{{ lane.name }}</option></select><small>Çakışan bir seans varsa atama reddedilir.</small></label><StatusBadge tone="info" label="Veritabanı çakışma kontrolü etkin" /></div><footer><button class="button button--secondary" @click="editing=null">Vazgeç</button><button class="button button--primary" :disabled="saving||selectedLane===editing.poolLaneId" @click="saveLane">{{ saving?'Kaydediliyor…':'Kulvarı Güncelle' }}</button></footer></aside></div>
</template>

<style scoped>
.pool-select{width:220px;grid-column:auto}.plan-toolbar{display:flex;align-items:center;gap:8px;margin-bottom:14px;padding:10px 12px;background:#fff;border:1px solid #d8e2ee}.plan-toolbar>strong{min-width:140px;text-align:center}.legend{margin-left:auto;display:flex;gap:15px;color:#49607c;font-size:11px}.legend span{display:flex;align-items:center;gap:5px}.legend i{width:9px;height:9px;border-radius:50%}.busy{background:#258bb5}.empty{background:#d8e2ee;border:1px solid #717781}.maintenance{background:#e39316}.closed{background:#ba1a1a}.timeline-card{background:#fff;border:1px solid #c1c7d2}.timeline-scroll{overflow:auto}.timeline{min-width:1500px}.timeline-head,.lane-row{display:grid;grid-template-columns:190px 1fr}.timeline-head{height:48px;background:#edf4ff;border-bottom:1px solid #c1c7d2}.lane-name{display:flex;align-items:center;gap:9px;padding:10px 14px;border-right:1px solid #c1c7d2}.lane-name svg{color:#258bb5}.lane-name strong,.lane-name span{display:block}.lane-name span{margin-top:3px;color:#5d6875;font-size:10px}.lane-name.head{font-size:11px;font-weight:800;letter-spacing:.05em;text-transform:uppercase}.hours{display:grid;grid-template-columns:repeat(16,1fr)}.hours span{display:grid;place-items:center;border-right:1px solid #d8e2ee;color:#49607c;font-size:10px}.lane-row{min-height:92px;border-bottom:1px solid #d8e2ee}.lane-row:last-child{border:0}.lane-track{position:relative;display:grid;grid-template-columns:repeat(16,1fr);background:#fbfdff}.gridline{border-right:1px solid #e5ebf1}.session-block{position:absolute;top:10px;bottom:10px;min-width:110px;overflow:hidden;padding:9px 10px;border:0;border-left:4px solid #258bb5;background:#dff2f8;color:#083c50;text-align:left}.session-block:hover{background:#c9ebf4}.session-block strong,.session-block span,.session-block small{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.session-block strong{font-size:11px}.session-block span{margin-top:4px;font-size:10px}.session-block small{display:flex;align-items:center;gap:3px;margin-top:5px}.session-maintenance{border-color:#e39316;background:#fff0d4}.session-closed,.session-cancelled{border-color:#ba1a1a;background:#ffdfdc}.drawer-backdrop{position:fixed;inset:0;z-index:120;background:rgba(5,29,47,.38)}.drawer{position:absolute;inset:0 0 0 auto;width:min(460px,100%);display:flex;flex-direction:column;background:#fff}.drawer header{display:flex;justify-content:space-between;align-items:flex-start;padding:20px;border-bottom:1px solid #d8e2ee}.drawer h2{margin:0}.drawer__body{flex:1;padding:20px}.drawer footer{display:flex;justify-content:flex-end;gap:8px;padding:16px 20px;border-top:1px solid #d8e2ee}@media(max-width:760px){.plan-toolbar{flex-wrap:wrap}.legend{width:100%;margin:6px 0 0;flex-wrap:wrap}.pool-select{width:100%}}
</style>
