<script setup lang="ts">
/* eslint vue/singleline-html-element-content-newline: "off", vue/max-attributes-per-line: "off", vue/html-self-closing: "off" */
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import { AlertCircle, CheckCircle2, Search, UserPlus, Users } from 'lucide-vue-next'
import InitialsAvatar from '@/components/InitialsAvatar.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import { apiFetch, money } from '@/lib/api'
import type { Participant } from '@/lib/types'

const route=useRoute(); const courseId=String(route.params.courseId)
const query=ref(''); const results=ref<Participant[]>([]); const searching=ref(false); const selected=ref<Participant|null>(null); const createNew=ref(false)
const loading=ref(false); const error=ref(''); const result=ref<{enrollmentId:string;status:string;waitlistPosition:number|null;agreedFeeAmountCents:number}|null>(null)
const form=ref({fullName:'',phone:'',email:'',birthDate:'',participantType:'external',guardianName:'',guardianPhone:'',sportsHistory:'',healthNotes:'',agreedFeeAmountCents:0})
const needsGuardian=computed(()=>!!form.value.birthDate&&new Date().getFullYear()-new Date(form.value.birthDate).getFullYear()<18)
let debounce:ReturnType<typeof globalThis.setTimeout>
function search(){globalThis.clearTimeout(debounce);debounce=globalThis.setTimeout(async()=>{if(query.value.trim().length<2){results.value=[];return}searching.value=true;try{const response=await apiFetch<{items:Participant[]}>(`/participants?query=${encodeURIComponent(query.value.trim())}`);results.value=response.items}catch(cause){error.value=cause instanceof Error?cause.message:'Arama yapılamadı.'}finally{searching.value=false}},250)}
function selectParticipant(person:Participant){selected.value=person;createNew.value=false;results.value=[];query.value=person.fullName}
function beginNew(){selected.value=null;createNew.value=true;results.value=[];if(query.value.trim())form.value.fullName=query.value.trim()}
async function submit(){loading.value=true;error.value='';try{let payload;if(selected.value){payload={participantId:selected.value.id,agreedFeeAmountCents:Number(form.value.agreedFeeAmountCents)}}else{const names=form.value.fullName.trim().split(/\s+/);if(names.length<2)throw new Error('Ad ve soyadı birlikte yazın.');payload={participant:{participantType:form.value.participantType,firstName:names.slice(0,-1).join(' '),lastName:names.at(-1),birthDate:form.value.birthDate||null,email:form.value.email||null,phone:form.value.phone||null,safetyNotes:[form.value.sportsHistory,form.value.healthNotes].filter(Boolean).join('\n')||null,guardian:needsGuardian.value?{fullName:form.value.guardianName,phone:form.value.guardianPhone}:undefined},agreedFeeAmountCents:Number(form.value.agreedFeeAmountCents)}}result.value=await apiFetch(`/courses/${courseId}/enrollments`,{method:'POST',body:JSON.stringify(payload)})}catch(cause){error.value=cause instanceof Error?cause.message:'Kursiyer kaydedilemedi.'}finally{loading.value=false}}
</script>

<template>
  <div class="page-header"><div><p class="eyebrow">Kurs kaydı</p><h1>Kursiyer Kaydet</h1><p>Önce mevcut kursiyeri arayın; yalnız bulunamazsa yeni kişi oluşturun.</p></div><RouterLink class="button button--secondary" :to="`/courses/${courseId}`">Kursa Dön</RouterLink></div>
  <div v-if="result" class="result-card card"><CheckCircle2 :size="42" /><div><p class="eyebrow">Kayıt tamamlandı</p><h2>{{ result.status==='waitlisted'?'Bekleme listesine alındı':'Kursa aktif kaydedildi' }}</h2><p>{{ result.status==='waitlisted'?`Bekleme sırası: ${result.waitlistPosition}`:'Kursiyer aktif listeye eklendi.' }}</p><strong>Onaylanan ücret: {{ money(result.agreedFeeAmountCents) }}</strong></div><div class="page-actions"><RouterLink class="button button--secondary" :to="`/courses/${courseId}`">Kurs Detayı</RouterLink><RouterLink class="button button--primary" :to="{path:'/payments',query:{enrollmentId:result.enrollmentId}}">Ödeme Kaydet</RouterLink></div></div>
  <form v-else class="enroll-layout" @submit.prevent="submit">
    <div class="stack">
      <section class="card"><div class="card__header"><h2><Search :size="19" />Mevcut Kursiyeri Ara</h2></div><div class="card__body search-box"><label class="field field--full"><span>Ad, telefon veya e-posta</span><input v-model="query" type="search" placeholder="En az iki karakter yazın" @input="search" /></label><span v-if="searching" class="muted">Aranıyor…</span><div v-if="results.length" class="search-results"><button v-for="person in results" :key="person.id" type="button" @click="selectParticipant(person)"><InitialsAvatar :name="person.fullName" size="sm" /><span><strong>{{ person.fullName }}</strong><small>{{ person.phone || person.email || 'İletişim bilgisi yok' }}</small></span><span>{{ person.activeEnrollmentCount || 0 }} aktif kayıt</span></button></div><button v-if="query.trim().length>=2&&!selected" class="button button--secondary" type="button" @click="beginNew"><UserPlus :size="17" />Yeni kursiyer oluştur</button></div></section>
      <section v-if="selected" class="card selected-person"><div class="card__body"><InitialsAvatar :name="selected.fullName" size="lg" /><div><p class="eyebrow">Seçili kursiyer</p><h2>{{ selected.fullName }}</h2><p>{{ selected.phone || selected.email || 'İletişim bilgisi yok' }}</p></div><button class="button button--secondary" type="button" @click="selected=null;query=''">Değiştir</button></div></section>
      <template v-if="createNew">
        <section class="card"><div class="card__header"><h2><Users :size="19" />Kursiyer Bilgileri</h2></div><div class="card__body form-grid"><label class="field"><span>Ad Soyad</span><input v-model.trim="form.fullName" required /></label><label class="field"><span>Telefon</span><input v-model.trim="form.phone" inputmode="tel" placeholder="0 (5XX) XXX XX XX" /></label><label class="field"><span>E-posta</span><input v-model.trim="form.email" inputmode="email" type="email" /></label><label class="field"><span>Doğum Tarihi</span><input v-model="form.birthDate" type="date" /></label><label class="field"><span>Kursiyer Türü</span><select v-model="form.participantType"><option value="external">Harici Kursiyer</option><option value="member">Üye</option></select></label><label class="field field--full"><span>Spor Geçmişi ve Deneyim</span><textarea v-model.trim="form.sportsHistory" placeholder="Operasyon için gerekli kısa bilgi" /></label></div></section>
        <section v-if="needsGuardian" class="card"><div class="card__header"><h2>Veli / Vasi Bilgileri</h2><StatusBadge tone="warning" label="18 yaş altı için gerekli" /></div><div class="card__body form-grid"><label class="field"><span>Veli Ad Soyad</span><input v-model.trim="form.guardianName" required /></label><label class="field"><span>Veli Telefon</span><input v-model.trim="form.guardianPhone" required inputmode="tel" /></label></div></section>
        <section class="card health-card"><div class="card__header"><h2>Sağlık Beyanı ve Notlar</h2></div><div class="card__body"><label class="field field--full"><span>Antrenörün bilmesi gereken gerekli sağlık bilgileri</span><textarea v-model.trim="form.healthNotes" placeholder="Alerji, kronik rahatsızlık veya kullanılan ilaç gibi gerekli bilgiler" /><small>Yalnız kurs güvenliği için gerekli bilgileri girin.</small></label></div></section>
      </template>
    </div>
    <aside class="stack"><section class="card card--accent"><div class="card__header"><h2>Kayıt Özeti</h2></div><div class="card__body stack"><label class="field field--full"><span>Onaylanan Dönem Ücreti (kuruş)</span><input v-model.number="form.agreedFeeAmountCents" min="0" type="number" /><small>{{ money(Number(form.agreedFeeAmountCents)) }}</small></label><div class="notice"><AlertCircle :size="18" /><span>Kontenjan doluysa kayıt başarısız olmaz; kursiyer sırayla bekleme listesine alınır.</span></div><button class="button button--primary button--block" :disabled="loading||(!selected&&!createNew)" type="submit">{{ loading?'Kaydediliyor…':'Kaydı Tamamla' }}</button></div></section><div v-if="error" class="notice notice--danger" role="alert"><AlertCircle :size="18" />{{ error }}</div></aside>
  </form>
</template>

<style scoped>
.enroll-layout{display:grid;grid-template-columns:minmax(0,2.3fr) minmax(280px,1fr);gap:20px}.card__header h2{display:flex;align-items:center;gap:8px}.search-box{display:grid;gap:12px}.search-results{display:grid;border:1px solid #c1c7d2}.search-results button{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:center;padding:11px;border:0;border-bottom:1px solid #d8e2ee;background:white;text-align:left}.search-results button:hover{background:#edf4ff}.search-results button:last-child{border:0}.search-results strong,.search-results small{display:block}.search-results small,.search-results>button>span:last-child{margin-top:3px;color:#5d6875;font-size:11px}.selected-person .card__body{display:grid;grid-template-columns:auto 1fr auto;gap:14px;align-items:center}.selected-person h2,.selected-person p{margin:0}.selected-person h2{font-size:20px}.selected-person p:not(.eyebrow){margin-top:4px;color:#5d6875}.health-card{border-left:4px solid #c4424a}.result-card{min-height:300px;display:grid;grid-template-columns:auto 1fr auto;gap:20px;align-items:center;padding:32px;border-top:4px solid #27845c}.result-card>svg{color:#27845c}.result-card h2{margin:0;font-size:28px}.result-card p:not(.eyebrow){color:#5d6875}@media(max-width:900px){.enroll-layout{grid-template-columns:1fr}.result-card{grid-template-columns:auto 1fr}.result-card .page-actions{grid-column:1/-1}}@media(max-width:600px){.search-results button{grid-template-columns:auto 1fr}.search-results>button>span:last-child{grid-column:2}.selected-person .card__body{grid-template-columns:auto 1fr}.selected-person .button{grid-column:1/-1}.result-card{grid-template-columns:1fr;text-align:center}.result-card>svg{margin:auto}}
</style>
