<script setup lang="ts">
/* eslint vue/singleline-html-element-content-newline: "off", vue/max-attributes-per-line: "off", vue/html-self-closing: "off" */
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
import { AlertCircle, CreditCard, Plus, ReceiptText, Search, X } from 'lucide-vue-next'
import InitialsAvatar from '@/components/InitialsAvatar.vue'
import StatePanel from '@/components/StatePanel.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import { ApiError, apiFetch, money, shortDate } from '@/lib/api'
import type { PaymentRecord } from '@/lib/types'
import { useAuthStore } from '@/stores/auth'

interface PaymentsResponse { items: PaymentRecord[] }
const route=useRoute();const auth=useAuthStore();const data=ref<PaymentsResponse|null>(null);const loading=ref(true);const error=ref('');const open=ref(typeof route.query.enrollmentId==='string');const saving=ref(false)
const filters=reactive({query:typeof route.query.query==='string'?route.query.query:'',dateFrom:'',dateTo:'',status:''})
const form=reactive({enrollmentId:typeof route.query.enrollmentId==='string'?route.query.enrollmentId:'',amount:0,method:'cash',reference:'',notes:'',allowOverpayment:false})
const canVoid=computed(()=>auth.user?.role==='owner'||auth.user?.role==='manager')
const displayItems=computed(()=>data.value?.items.filter((item)=>{const date=item.recordedAt.slice(0,10);return (!filters.status||item.status===filters.status)&&(!filters.dateFrom||date>=filters.dateFrom)&&(!filters.dateTo||date<=filters.dateTo)})||[])
const paymentSummary=computed(()=>({recordedTotalCents:displayItems.value.filter((item)=>item.status==='recorded').reduce((sum,item)=>sum+item.amountCents,0),voidedTotalCents:displayItems.value.filter((item)=>item.status==='voided').reduce((sum,item)=>sum+item.amountCents,0),recordCount:displayItems.value.length}))
let debounce:ReturnType<typeof globalThis.setTimeout>
async function load(){loading.value=true;error.value='';const params=new globalThis.URLSearchParams({page:'1',pageSize:'100'});if(filters.query)params.set('query',filters.query);try{data.value=await apiFetch<PaymentsResponse>(`/payments?${params}`)}catch(cause){error.value=cause instanceof Error?cause.message:'Tahsilatlar alınamadı.'}finally{loading.value=false}}
async function record(){saving.value=true;error.value='';try{await apiFetch(`/enrollments/${form.enrollmentId}/payments`,{method:'POST',body:JSON.stringify({amountCents:Math.round(Number(form.amount)*100),method:form.method,reference:form.reference||null,note:form.notes||null,allowOverpayment:form.allowOverpayment})});open.value=false;Object.assign(form,{enrollmentId:'',amount:0,method:'cash',reference:'',notes:'',allowOverpayment:false});await load()}catch(cause){error.value=cause instanceof ApiError?cause.message:'Tahsilat kaydedilemedi.'}finally{saving.value=false}}
async function voidPayment(payment:PaymentRecord){const reason=globalThis.prompt('Tahsilatı geçersiz kılma nedenini yazın:');if(!reason?.trim())return;try{await apiFetch(`/payments/${payment.id}/void`,{method:'POST',body:JSON.stringify({reason:reason.trim()})});await load()}catch(cause){error.value=cause instanceof ApiError?cause.message:'Tahsilat geçersiz kılınamadı.'}}
watch(filters,()=>{globalThis.clearTimeout(debounce);debounce=globalThis.setTimeout(load,300)});onMounted(load)
</script>

<template>
  <div class="page-header"><div><p class="eyebrow">Manuel kayıt</p><h1>Tahsilatlar</h1><p>Kurs ödemelerini kayıt altına alın; bu ekran ödeme işlemi gerçekleştirmez.</p></div><button class="button button--primary" @click="open=true"><Plus :size="17" />Ödeme Kaydet</button></div>
  <div class="notice"><AlertCircle :size="18" /><span>Tüm tahsilatlar personel tarafından girilen muhasebe kayıtlarıdır. Çevrimiçi kart işlemi yapılmaz.</span></div>
  <section v-if="data" class="payment-summary"><div><ReceiptText :size="21" /><span>Kaydedilen</span><strong>{{ money(paymentSummary.recordedTotalCents) }}</strong></div><div><X :size="21" /><span>Geçersiz</span><strong>{{ money(paymentSummary.voidedTotalCents) }}</strong></div><div><CreditCard :size="21" /><span>Kayıt Sayısı</span><strong>{{ paymentSummary.recordCount }}</strong></div></section>
  <section class="filters payment-filters"><label class="field"><span>Kursiyer veya kurs</span><div class="search-field"><Search :size="16" /><input v-model="filters.query" placeholder="Ad soyad veya kurs" /></div></label><label class="field"><span>Başlangıç</span><input v-model="filters.dateFrom" type="date" /></label><label class="field"><span>Bitiş</span><input v-model="filters.dateTo" type="date" /></label><label class="field"><span>Durum</span><select v-model="filters.status"><option value="">Tümü</option><option value="recorded">Kaydedildi</option><option value="voided">Geçersiz</option></select></label></section>
  <StatePanel v-if="loading" state="loading" /><StatePanel v-else-if="error&&!data" state="error" :message="error" @retry="load" /><StatePanel v-else-if="!displayItems.length" state="empty" title="Tahsilat kaydı yok" message="Seçili ölçütlerde manuel ödeme kaydı bulunmuyor." />
  <section v-else class="card table-wrap"><table class="data-table"><thead><tr><th>Kursiyer</th><th>Kurs</th><th>Tarih</th><th>Tutar</th><th>Yöntem</th><th>Kaydeden</th><th>Durum</th><th><span class="sr-only">İşlem</span></th></tr></thead><tbody><tr v-for="payment in displayItems" :key="payment.id"><td><div class="person-cell"><InitialsAvatar :name="payment.participantName" size="sm" /><strong>{{ payment.participantName }}</strong></div></td><td>{{ payment.courseName }}</td><td>{{ shortDate(payment.recordedAt) }}</td><td><strong>{{ money(payment.amountCents) }}</strong></td><td>{{ {cash:'Nakit',card_terminal:'Kart Terminali',bank_transfer:'Banka Transferi',other:'Diğer'}[payment.method]||payment.method }}</td><td>{{ payment.recordedBy }}</td><td><StatusBadge :tone="payment.status==='recorded'?'success':'neutral'" :label="payment.status==='recorded'?'Kaydedildi':'Geçersiz'" /></td><td><button v-if="payment.status==='recorded'&&canVoid" class="button button--danger" @click="voidPayment(payment)">Geçersiz Kıl</button></td></tr></tbody></table></section>
  <div v-if="open" class="modal-backdrop" @click.self="open=false"><form class="modal card" role="dialog" aria-modal="true" aria-labelledby="payment-title" @submit.prevent="record"><div class="card__header"><h2 id="payment-title">Manuel Ödeme Kaydı</h2><button class="icon-button" type="button" aria-label="Kapat" @click="open=false"><X :size="20" /></button></div><div class="card__body form-grid"><label class="field field--full"><span>Kurs Kaydı / Enrollment ID</span><input v-model.trim="form.enrollmentId" required /></label><label class="field"><span>Tutar (₺)</span><input v-model.number="form.amount" min="0.01" step="0.01" required type="number" /></label><label class="field"><span>Yöntem</span><select v-model="form.method"><option value="cash">Nakit</option><option value="card_terminal">Kart Terminali</option><option value="bank_transfer">Banka Transferi</option><option value="other">Diğer</option></select></label><label class="field field--full"><span>Referans</span><input v-model.trim="form.reference" placeholder="Makbuz veya dekont referansı (isteğe bağlı)" /></label><label class="field field--full"><span>Not</span><textarea v-model.trim="form.notes" /></label><label v-if="canVoid" class="check-line field--full"><input v-model="form.allowOverpayment" type="checkbox" /><span>Yetkim kapsamında fazla ödemeye açıkça izin veriyorum.</span></label><div v-if="error" class="notice notice--danger field--full">{{ error }}</div></div><footer class="modal-footer"><span><b>{{ money(Math.round(Number(form.amount)*100)) }}</b> manuel kayıt</span><div><button class="button button--secondary" type="button" @click="open=false">Vazgeç</button><button class="button button--primary" :disabled="saving">{{ saving?'Kaydediliyor…':'Ödemeyi Kaydet' }}</button></div></footer></form></div>
</template>

<style scoped>
.payment-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin:16px 0}.payment-summary>div{display:grid;grid-template-columns:auto 1fr;gap:5px 10px;padding:16px;background:white;border:1px solid #d8e2ee;border-left:4px solid #258bb5}.payment-summary svg{grid-row:1/3;color:#258bb5}.payment-summary span{color:#49607c;font-size:10px;text-transform:uppercase}.payment-summary strong{font-size:22px}.payment-filters{grid-template-columns:2fr 1fr 1fr 1fr}.search-field{display:flex;align-items:center;gap:6px;min-height:42px;padding:0 10px;background:white;border:1px solid #8fa3b7}.search-field input{border:0;box-shadow:none;min-height:auto;padding:0}.modal-backdrop{position:fixed;inset:0;z-index:150;display:grid;place-items:center;padding:18px;background:rgba(5,29,47,.52)}.modal{width:min(660px,100%);max-height:calc(100vh - 36px);overflow:auto}.modal-footer{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:15px 18px;border-top:1px solid #d8e2ee;background:#f8fbff}.modal-footer>div{display:flex;gap:8px}.modal-footer span{font-size:12px;color:#49607c}.modal-footer b{color:#051d2f}@media(max-width:800px){.payment-summary{grid-template-columns:1fr}.payment-filters{grid-template-columns:1fr 1fr}}@media(max-width:500px){.payment-filters{grid-template-columns:1fr}.modal-footer{align-items:stretch;flex-direction:column}.modal-footer>div{display:grid;grid-template-columns:1fr 1fr}}
</style>
