<script setup lang="ts">
/* eslint vue/singleline-html-element-content-newline: "off", vue/max-attributes-per-line: "off", vue/html-self-closing: "off" */
import { computed, onMounted, reactive, ref } from 'vue'
import { AlertCircle, CheckCircle2, ClipboardCheck, Droplets, History, Save, Thermometer } from 'lucide-vue-next'
import StatePanel from '@/components/StatePanel.vue'
import StatusBadge from '@/components/StatusBadge.vue'
import { ApiError, apiFetch, shortDate, shortTime } from '@/lib/api'
import type { PoolChecksResponse } from '@/lib/types'
import { useAuthStore } from '@/stores/auth'

const data=ref<PoolChecksResponse|null>(null);const loading=ref(true);const saving=ref(false);const error=ref('');const success=ref('');const selectedPool=ref('');const notes=ref('');const values=reactive<Record<string,string|number|boolean>>({})
const auth=useAuthStore();const facility=reactive({cleaningStatus:'ok',equipmentStatus:'ok',changingRoomStatus:'ok'})
const selectedPoolName=computed(()=>data.value?.pools.find(pool=>pool.id===selectedPool.value)?.name||'Havuz')
async function load(){loading.value=true;error.value='';try{data.value=await apiFetch<PoolChecksResponse>('/pool-checks');if(!selectedPool.value&&data.value.pools[0])selectedPool.value=data.value.pools[0].id;for(const item of data.value.definitions){if(!(item.id in values))values[item.id]=item.inputType==='boolean'?false:''}}catch(cause){error.value=cause instanceof Error?cause.message:'Havuz kontrolleri alınamadı.'}finally{loading.value=false}}
async function submit(){saving.value=true;error.value='';success.value='';try{await apiFetch('/pool-checks',{method:'POST',body:JSON.stringify({poolId:selectedPool.value,...facility,note:notes.value.trim()||null,values:Object.entries(values).map(([definitionId,value])=>({definitionId,value}))})});success.value='Havuz kontrolü kaydedildi.';notes.value='';await load()}catch(cause){error.value=cause instanceof ApiError?cause.message:'Kontrol kaydedilemedi.'}finally{saving.value=false}}
const tone=(status:string)=>status==='ok'?'success':status==='attention'?'warning':'neutral'
const label=(status:string)=>({ok:'Normal',attention:'Dikkat Gerekli',not_checked:'Kontrol Edilmedi'}[status]||status)
onMounted(load)
</script>

<template>
  <div class="page-header"><div><p class="eyebrow">Tesis operasyonu</p><h1>Havuz Kontrolleri</h1><p>Tesis tarafından tanımlanan ölçümleri ve saha kontrollerini kaydedin.</p></div><label class="field pool-filter"><span>Havuz</span><select v-model="selectedPool"><option v-for="pool in data?.pools||[]" :key="pool.id" :value="pool.id">{{ pool.name }}</option></select></label></div>
  <StatePanel v-if="loading" state="loading" />
  <StatePanel v-else-if="error&&!data" state="error" :message="error" @retry="load" />
  <template v-else-if="data">
    <div class="pool-summary"><div class="temperature"><Thermometer :size="28" /><div><span>Son Kontrol</span><strong>{{ data.latest?`${shortDate(data.latest.checkedAt)} · ${shortTime(data.latest.checkedAt)}`:'Henüz yok' }}</strong></div></div><div><span>Havuz</span><strong>{{ data.latest?.poolName||selectedPoolName }}</strong></div><div><span>Sorumlu</span><strong>{{ data.latest?.checkedBy||'—' }}</strong></div><StatusBadge v-if="data.latest" :tone="tone(data.latest.status)" :label="label(data.latest.status)" /></div>
    <div v-if="error" class="notice notice--danger"><AlertCircle :size="18" />{{ error }}</div><div v-if="success" class="notice notice--success"><CheckCircle2 :size="18" />{{ success }}</div>
    <div class="checks-layout">
      <form v-if="auth.isManager" class="card" @submit.prevent="submit"><div class="card__header"><h2><ClipboardCheck :size="20" />Yeni Kontrol · {{ selectedPoolName }}</h2></div><div v-if="data.definitions.length" class="check-fields"><label class="field"><span>Temizlik Durumu</span><select v-model="facility.cleaningStatus"><option value="ok">Normal</option><option value="attention">Dikkat Gerekli</option><option value="not_checked">Kontrol Edilmedi</option></select></label><label class="field"><span>Ekipman Durumu</span><select v-model="facility.equipmentStatus"><option value="ok">Normal</option><option value="attention">Dikkat Gerekli</option><option value="not_checked">Kontrol Edilmedi</option></select></label><label class="field"><span>Soyunma Odaları</span><select v-model="facility.changingRoomStatus"><option value="ok">Normal</option><option value="attention">Dikkat Gerekli</option><option value="not_checked">Kontrol Edilmedi</option></select></label><label v-for="definition in data.definitions" :key="definition.id" class="check-field" :class="{boolean:definition.inputType==='boolean'}"><template v-if="definition.inputType==='boolean'"><input v-model="values[definition.id]" type="checkbox" /><span>{{ definition.label }}</span></template><template v-else><span>{{ definition.label }}<small v-if="definition.unit">({{ definition.unit }})</small></span><div><input v-model="values[definition.id]" :required="definition.required" :type="definition.inputType==='number'?'number':'text'" :step="definition.inputType==='number'?'any':undefined" /><em v-if="definition.minValue!=null||definition.maxValue!=null">Beklenen: {{ definition.minValue??'—' }} – {{ definition.maxValue??'—' }} {{ definition.unit||'' }}</em></div></template></label><label class="field field--full"><span>Operasyon Notu</span><textarea v-model="notes" placeholder="Kontrol sırasında gözlenen gerekli bilgileri yazın" /></label></div><StatePanel v-else state="empty" title="Kontrol alanı tanımlı değil" message="Tesis yöneticisi ölçüm ve kontrol alanlarını tanımlamalı." /><footer class="check-footer"><p>Durumlar tesis tarafından belirlenen aralıklara göre hesaplanır; hukuki uygunluk beyanı değildir.</p><button class="button button--primary" :disabled="saving||!selectedPool||!data.definitions.length"><Save :size="18" />{{ saving?'Kaydediliyor…':'Kontrolü Kaydet' }}</button></footer></form>
      <div v-else class="notice"><AlertCircle :size="18" /><span>Resepsiyon rolü kontrol geçmişini görüntüleyebilir; yeni kontrol kaydı yöneticiler tarafından oluşturulur.</span></div>
      <aside class="card"><div class="card__header"><h2><History :size="20" />Kontrol Geçmişi</h2></div><div v-if="data.history.length" class="history-list"><article v-for="item in data.history" :key="item.id"><div class="history-icon"><Droplets :size="18" /></div><div><strong>{{ item.poolName }}</strong><p>{{ item.summary||'Kontrol değerleri kaydedildi.' }}</p><small>{{ item.checkedBy }} · {{ shortDate(item.checkedAt) }} {{ shortTime(item.checkedAt) }}</small></div><StatusBadge :tone="tone(item.status)" :label="label(item.status)" /></article></div><StatePanel v-else state="empty" title="Geçmiş kontrol yok" /></aside>
    </div>
  </template>
</template>

<style scoped>
.pool-filter{width:220px;grid-column:auto}.pool-summary{display:flex;align-items:center;gap:24px;min-height:82px;margin-bottom:16px;padding:14px 18px;background:#102a43;color:#e8f2ff;border-radius:6px}.pool-summary>div{padding-right:22px;border-right:1px solid rgba(255,255,255,.2)}.pool-summary .temperature{display:flex;align-items:center;gap:10px;margin-right:auto}.pool-summary span,.pool-summary strong{display:block}.pool-summary span{color:#b9cad8;font-size:10px;letter-spacing:.06em;text-transform:uppercase}.pool-summary strong{margin-top:4px;font-size:14px}.checks-layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(320px,1fr);gap:20px}.card__header h2{display:flex;align-items:center;gap:8px}.check-fields{display:grid;grid-template-columns:repeat(2,1fr);gap:1px;background:#d8e2ee}.check-field{min-height:98px;display:flex;align-items:center;justify-content:space-between;gap:15px;padding:16px;background:#fff}.check-field>span{font-weight:700}.check-field>span small{margin-left:4px;color:#5d6875;font-weight:400}.check-field>div{text-align:right}.check-field input:not([type=checkbox]){width:150px;min-height:42px;padding:8px 10px;border:1px solid #8fa3b7;border-radius:4px}.check-field em{display:block;margin-top:5px;color:#5d6875;font-size:10px;font-style:normal}.check-field.boolean{justify-content:flex-start}.check-field.boolean input{width:22px;height:22px;accent-color:#1769aa}.check-fields .field{padding:16px;background:#fff}.check-footer{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:16px 18px;border-top:1px solid #d8e2ee;background:#f8fbff}.check-footer p{max-width:580px;margin:0;color:#5d6875;font-size:11px}.history-list{display:grid}.history-list article{display:grid;grid-template-columns:auto 1fr auto;gap:10px;align-items:start;padding:14px;border-bottom:1px solid #d8e2ee}.history-list article:last-child{border:0}.history-icon{width:34px;height:34px;display:grid;place-items:center;background:#dff2f8;color:#005472}.history-list p{margin:4px 0;color:#425263;font-size:12px}.history-list small{color:#5d6875;font-size:10px}@media(max-width:1000px){.checks-layout{grid-template-columns:1fr}}@media(max-width:650px){.pool-filter{width:100%}.pool-summary{align-items:flex-start;flex-wrap:wrap}.pool-summary .temperature{width:100%}.pool-summary>div{border:0}.check-fields{grid-template-columns:1fr}.check-footer{align-items:stretch;flex-direction:column}}
</style>
